### ISSUE TITLE
Error when building toolchain on Ubunut 24.04

### ISSUE THREAD

**Issue by samuelh2005** [Bananymous/banan-os#1]
I've installed all the packages and ran `./bos toolchain`. After a while, I've got a couple errors:
* `fakeroot: database file `/home/samro/banan-os/script/../build/fakeroot-context' does not exist.`
* `version `GLIBC_2.34' not found (required by /usr/lib/x86_64-linux-gnu/libfakeroot/libfakeroot-sysv.so)`
* `ninja: build stopped: subcommand failed.`

Part of log (the full log does not fit in my terminal):
```
make[2]: Leaving directory '/home/samro/banan-os/build/toolchain/grub-2.06/build-x86_64/po'
Making install in docs
make[2]: Entering directory '/home/samro/banan-os/build/toolchain/grub-2.06/build-x86_64/docs'
make[3]: Entering directory '/home/samro/banan-os/build/toolchain/grub-2.06/build-x86_64/docs'
make[3]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/home/samro/banan-os/script/../toolchain/local/share/info'
 /usr/bin/install -c -m 644 ../../docs/grub.info ../../docs/grub.info-1 ../../docs/grub.info-2 ../../docs/grub-dev.info '/home/samro/banan-os/script/../toolchain/local/share/info'
 install-info --info-dir='/home/samro/banan-os/script/../toolchain/local/share/info' '/home/samro/banan-os/script/../toolchain/local/share/info/grub.info'
 install-info --info-dir='/home/samro/banan-os/script/../toolchain/local/share/info' '/home/samro/banan-os/script/../toolchain/local/share/info/grub-dev.info'
make[3]: Leaving directory '/home/samro/banan-os/build/toolchain/grub-2.06/build-x86_64/docs'
make[2]: Leaving directory '/home/samro/banan-os/build/toolchain/grub-2.06/build-x86_64/docs'
Making install in util/bash-completion.d
make[2]: Entering directory '/home/samro/banan-os/build/toolchain/grub-2.06/build-x86_64/util/bash-completion.d'
make[3]: Entering directory '/home/samro/banan-os/build/toolchain/grub-2.06/build-x86_64/util/bash-completion.d'
make[3]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/home/samro/banan-os/script/../toolchain/local/etc/bash_completion.d'
 /usr/bin/install -c -m 644 grub '/home/samro/banan-os/script/../toolchain/local/etc/bash_completion.d'
make[3]: Leaving directory '/home/samro/banan-os/build/toolchain/grub-2.06/build-x86_64/util/bash-completion.d'
make[2]: Leaving directory '/home/samro/banan-os/build/toolchain/grub-2.06/build-x86_64/util/bash-completion.d'
make[1]: Leaving directory '/home/samro/banan-os/build/toolchain/grub-2.06/build-x86_64'
-- The CXX compiler identification is GNU 12.2.0
-- The C compiler identification is GNU 12.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /home/samro/banan-os/toolchain/local/bin/x86_64-banan_os-gcc
System is unknown to cmake, create:
Platform/banan-os to use this system, please post your config file on discourse.cmake.org so it can be added to cmake
-- Detecting CXX compiler ABI info
System is unknown to cmake, create:
Platform/banan-os to use this system, please post your config file on discourse.cmake.org so it can be added to cmake
-- Detecting CXX compiler ABI info - failed
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
System is unknown to cmake, create:
Platform/banan-os to use this system, please post your config file on discourse.cmake.org so it can be added to cmake
-- Detecting C compiler ABI info - failed
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done (0.4s)
-- Generating done (0.1s)
-- Build files have been written to: /home/samro/banan-os/build
fakeroot: database file `/home/samro/banan-os/script/../build/fakeroot-context' does not exist.
[1/37] cd /home/samro/banan-os/build && /snap/cmake/1...ot && tar xf /home/samro/banan-os/base-sysroot.tar.gz
FAILED: CMakeFiles/sysroot /home/samro/banan-os/build/CMakeFiles/sysroot
cd /home/samro/banan-os/build && /snap/cmake/1384/bin/cmake -E make_directory /home/samro/banan-os/script/../build/sysroot && cd /home/samro/banan-os/script/../build/sysroot && tar xf /home/samro/banan-os/base-sysroot.tar.gz
/snap/cmake/1384/bin/cmake: /snap/core20/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /usr/lib/x86_64-linux-gnu/libfakeroot/libfakeroot-sysv.so)
/snap/cmake/1384/bin/cmake: /snap/core20/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/lib/x86_64-linux-gnu/libfakeroot/libfakeroot-sysv.so)
[2/37] cd /home/samro/banan-os/build/libc && /home/sa...home/samro/banan-os/libc/arch/x86_64/crtn.S -o crtn.o
ninja: build stopped: subcommand failed.
```

**Comment by Bananymous** [comment]
That fakeroot error is "normal". It happens whenever you run the build script for the first time, and fakeroot has not yet saved any context. That won't lead to any failures in the build process, and will disappear on subsequent builds.

I'm currently on a holiday and I am coming back on the weekend. I will investigate the glibc version requirement error after that.

What version of glibc do you have installed? `ldd --version` should print that out. And `/home/samro/banan-os/toolchain/local/bin/x86_64-banan_os-ldd --version` should print the version the toolchain uses.

And the last error from ninja is caused by the glibc version mismatch

**Comment by samuelh2005** [comment]
Thanks,

`ldd --version` says:

```
ldd (Ubuntu GLIBC 2.39-0ubuntu8.1) 2.39
Copyright (C) 2024 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

`/home/samro/banan-os/toolchain/local/bin/x86_64-banan_os-ldd --version` says:

```
-bash: /home/samro/banan-os/toolchain/local/bin/x86_64-banan_os-ldd: No such file or directory
```
probably because the compilation hasn't finished yet.

Some of the utilities have been compiled:

`/home/samro/banan-os/toolchain/local/bin/` says:

```
grub-editenv          grub-mkrescue              x86_64-banan_os-elfedit     x86_64-banan_os-ld
grub-file             grub-mkstandalone          x86_64-banan_os-g++         x86_64-banan_os-ld.bfd
grub-fstest           grub-render-label          x86_64-banan_os-gcc         x86_64-banan_os-lto-dump
grub-glue-efi         grub-script-check          x86_64-banan_os-gcc-12.2.0  x86_64-banan_os-nm
grub-kbdcomp          grub-syslinux2cfg          x86_64-banan_os-gcc-ar      x86_64-banan_os-objcopy
grub-menulst2cfg      x86_64-banan_os-addr2line  x86_64-banan_os-gcc-nm      x86_64-banan_os-objdump
grub-mkimage          x86_64-banan_os-ar         x86_64-banan_os-gcc-ranlib  x86_64-banan_os-ranlib
grub-mklayout         x86_64-banan_os-as         x86_64-banan_os-gcov        x86_64-banan_os-readelf
grub-mknetdir         x86_64-banan_os-c++        x86_64-banan_os-gcov-dump   x86_64-banan_os-size
grub-mkpasswd-pbkdf2  x86_64-banan_os-c++filt    x86_64-banan_os-gcov-tool   x86_64-banan_os-strings
grub-mkrelpath        x86_64-banan_os-cpp        x86_64-banan_os-gprof       x86_64-banan_os-strip
```

**Comment by Bananymous** [comment]
Oh lld is part of LLVM, so ofcourse my toolchain does not contain it :D 

But yeah that error is kind of weird. Why is fakeroot requiring a version of glibc that is not available on the system. I guess its some snap/apt version mismatch. I'll have to look into this.

**Comment by Bananymous** [comment]
I have been working on a docker based build system which should allow compilation to work on any host system.

There was just some loop device problem that I did not have time to look at properly.

**Comment by samuelh2005** [comment]
For loop devices I think the container needs to be [privileged](https://docs.docker.com/reference/cli/docker/container/run/#privileged)

**Comment by Bananymous** [comment]
Yeah I did figure that out, but iirc the problem was with removing old loop devices. `losetup -d ...` did not free the loop device and later builds always allocate a new loop device.

**Comment by ghost** [comment]
> I have been working on a docker based build system which should allow compilation to work on any host system.
> 
> There was just some loop device problem that I did not have time to look at properly.

Now that I think about it... I should probably make use of Docker sometime

**Comment by Bananymous** [comment]
As I suspected, the problem was with snap. The build system works fine on clean ubuntu 24.04 installation with only packages specified in the README.md installed. When I tried the install script with cmake installed from snap, I got the same error as you reported.

I will push an update to the build script once I have done some testing on my changes. The new system always downloads "correct" version of cmake without attempting to use one provided by the host.

**Comment by samuelh2005** [comment]
Excellent, I will try that once it is done.

**Comment by Bananymous** [comment]
This should now be fixed in af8fa4014f. Make sure to re-run `./bos toolchain` and rebuild gcc (as libstdc++ build failed previously).

**Comment by samuelh2005** [comment]
Looks like the toolchain successfully compiles now, and everything else:

![image](https://github.com/Bananymous/banan-os/assets/41990982/d7f9d0e6-f70a-4560-ae27-236265159db9)

**Comment by Bananymous** [comment]
Oh wow, I did not know that WSL works! Ubuntu 24.04 seems to have fixed some loop device problems. I knew that my OS did not work in WSL with Ubuntu 22.04 and I thought the problem was fully in WSL.

You can add yourself to group "kvm" so you can access it (WSL restart is probably needed). This will allow `./bos qemu` to work and enable some configurations.

**Comment by samuelh2005** [comment]
Seems like WSL does not support KVM:
```
$ dmesg | grep kvm
[    0.108056] kvm: no hardware support
[    0.108059] kvm: no hardware support
```

Apart from that, QEMU without KVM runs fast enough anyway.
